/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_utils_JNIUtils */

#ifndef _Included_com_example_utils_JNIUtils
#define _Included_com_example_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_utils_JNIUtils
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_utils_JNIUtils_helloJni
  (JNIEnv *, jclass);

/*
 * Class:     com_example_utils_JNIUtils
 * Method:    addCal
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_utils_JNIUtils_addCal
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
